"""Liquid US stocks universe (~190 names). Add/remove tickers freely."""
UNIVERSE = """
AAPL MSFT NVDA AMZN GOOGL META TSLA AVGO ORCL ADBE CRM AMD NFLX INTC QCOM TXN AMAT MU LRCX KLAC
ANET PANW CRWD SNPS CDNS NOW INTU UBER SHOP PLTR SNOW DDOG NET ZS MDB TEAM WDAY FTNT ABNB BKNG
MELI ARM SMCI MRVL ON NXPI ADI ADSK TTD DASH RBLX APP
JPM BAC WFC GS MS C SCHW BLK AXP V MA PYPL COF USB SPGI MCO ICE CME COIN HOOD SOFI
LLY UNH JNJ ABBV MRK PFE TMO ABT DHR ISRG VRTX REGN AMGN GILD BSX SYK MDT CVS CI ELV HCA ZTS IDXX DXCM
WMT COST HD LOW TGT NKE SBUX MCD CMG LULU DIS KO PEP PG PM MDLZ TJX ROST DECK ULTA ORLY AZO
CAT DE HON GE RTX LMT NOC BA UPS FDX UNP ETN EMR XOM CVX COP SLB EOG OXY LIN APD NEE DUK SO
T VZ TMUS CMCSA CSCO IBM ACN AMT PLD EQIX WM RSG F GM
""".split()
UNIVERSE = sorted(set(UNIVERSE))
